package Random::SciFi;
use v5.10.0;
use strict;
use warnings;
use Exporter qw(import);

use Random::Alpha qw(random_alpha);

our $VERSION   = '1.000';
our @EXPORT_OK = qw(random_HHGTTG_sector random_MIB_agent);

sub random_letters {
  my ($number) = @_;
  my $letter = sub { random_alpha('upper case') };
  my $letters;
  $letters .= &$letter for (1..$number);
  return $letters;
}

sub random_HHGTTG_sector {
  my @types = qw(Active Heavy Light Over Plural Passive Single Under);
  my $Greek = sub { random_alpha('Greek') };
  my $type  = sub { $types[rand @types] };
  return random_letters(2)." ".&$type." ".random_letters(1)." ".&$Greek;
}

sub random_MIB_agent {
  my @letters = (1, 2);
  my $letter  = $letters[rand @letters];
  return random_letters($letter);
}

=pod

=encoding utf8

=head1 NAME

B<Random::SciFi> returns a random I<Hitckhikers Guide to the Galaxy> (HHGTTG) sector or a random I<Men in Black> (MiB) agent id.

=head1 VERSION

This document describes Random::SciFi version 1.000.

=head1 SYNOPSIS

  use Random::SciFi qw(random_HHGTTG_sector random_MIB_agent);

  my $random_HHGTTG_sector = random_HHGTTG_sector(); # returns a random sector based on HHGTTG sectors mentioned.
  my $random_MIB_agent     = random_MIB_agent();     # returns a random MiB agent, either single or double letter.

=head1 DESCRIPTION

Random::SciFi returns a random I<Hitckhikers Guide to the Galaxy> (HHGTTG) sector or a random I<Men in Black> (MiB) agent id.

=head2 random_HHGTTG_sector

  random_HHGTTG_sector();

C<random_HHGTTG_sector> returns a random sector of the universe in I<The Hitchhikers Guide to the Galaxy> format.

The returned string starts with two random uppercase letters of the English alphabet, then is given a (for lack of a better term) type, one more uppercase letter of the English alphabet, and ending with a spelled out letter of the Greek alphabet. In the HHGTTG, Earth's sector is C<ZZ Plural Z Alpha>. Here are some sample sectors generated by this function.

  QJ Passive X Chi
  IO Heavy Z Nu
  MV Single P Mu
  PB Over Z Omicron
  IR Plural O Iota

=head2 random_MIB_agent

  random_MIB_agent();

C<random_MIB_agent> returns an identifier in the style of the I<Men in Black> frachise.

The returned string is one or two random uppercase letters of the English alphabet. Agent identifiers in the film series include: K, J, Z, O, L, M, H, C, and AA. Z is pronounced Zed.

=head1 DEPENDENCIES

Random::SciFi depends on L<Random::Alpha> and L<Exporter>.

Random::Alpha depends on L<Fancy::Rand> and L<Util::Data>.

=head1 AUTHOR

Lady Aleena

=head1 LICENCE AND COPYRIGHT

This module is free software; you can redistribute it and/or modify it under the same terms as Perl itself. See L<perlartistic>.

Copyright © 2020, Lady Aleena C<<aleena@cpan.org>>. All rights reserved.

=cut

1;